### ISSUE TITLE
Crear un modelo Playlist

### ISSUE THREAD

**Issue by ework** [ework/IS-2016-Team-2#36]
Crear un modelo Playlist donde un usuario pueda tener una lista de canciones.

**Importante**
Vamos a trabajar las ramas de la siguiente forma.
Supongamos que este es el Issue #1000 y mi nombre es Juanito lo que debes hacer es:
- Para realizar una nueva tarea, cambiarnos a la rama master.
- git checkout master
- Actualizar todas las ramas
- git pull
- Crear nuestra propia rama
- git checkout -b Issue#1000-Juanito
- Ya en nuestra rama, hacemos los cambios
- git add ...
- git commit -m "..."
- git push origin Issue#1000-Juanito
- Van a la página de git y crean pull request, de mi fork master al nombre de su rama.
- Esto último háganlo con cuidado, no creen el pull request al repo del profesor, eso se hace luego.
- Bueno y lo dejan ahi para que yo lo revice primero.
- Yo siempre voy a dar merge, a menos que les diga que lo hagan ustedes.

**Comment by SebastianWilde** [comment]
Esa no es una relación one to many entre usuario y canciones?

**Comment by ework** [comment]
Si es esa relación.

**Comment by SebastianWilde** [comment]
No puedo hacer mi issue falta la clase canción

**Comment by SebastianWilde** [comment]
No puedo hacer git push me sale este @ework 

sebastian@LenovoZ5070:~/Documentos/6semestre/IngSoft2/Practica/MusicPlayer$ git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': SebastianWilde
Password for 'https://SebastianWilde@github.com': 
To https://github.com/ework/is2-2016-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/ework/is2-2016-1.git'
consejo: Updates were rejected because a pushed branch tip is behind its remote
consejo: counterpart. If you did not intend to push that branch, you may want to
consejo: specify branches to push or set the 'push.default' configuration variable
consejo: to 'simple', 'current' or 'upstream' to push only the current branch.

**Comment by SebastianWilde** [comment]
Issue terminado

**Comment by ework** [comment]
Tenías que pushear con origin, no lo olvides :+1:
